### ISSUE TITLE
added the code in and get this error

### ISSUE THREAD

**Issue by MaximKing1** [RPGTheGreat/anti-spam#2]
so when adding in the template code it has this error

**Comment by MaximKing1** [comment]
`ReferenceError: antiSpam is not defined
    at Client.<anonymous> (/root/Strider/index.js:84:44)
    at Client.emit (events.js:327:22)
    at Client.EventEmitter.emit (domain.js:486:12)
    at MessageCreateAction.handle (/root/Strider/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/root/Strider/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/Strider/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/root/Strider/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/root/Strider/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/root/Strider/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.EventEmitter.emit (domain.js:486:12)
    at Receiver.receiverOnMessage (/root/Strider/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.EventEmitter.emit (domain.js:486:12)
    at Receiver.dataMessage (/root/Strider/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/root/Strider/node_modules/ws/lib/receiver.js:367:17)`

**Comment by MaximKing1** [comment]
this is the code im using
`client.on('ready', async(ready) => {
  // Module Configuration Constructor
   AntiSpam(client, {
        limitUntilWarn: 3, // The amount of messages allowed to send within the interval(time) before getting a warn.
        limitUntilMuted: 5, // The amount of messages allowed to send within the interval(time) before getting a muted.
        interval: 2000, // The interval(time) where the messages are sent. Practically if member X sent 5+ messages within 2 seconds, he get muted. (1000 milliseconds = 1 second, 2000 milliseconds = 2 seconds etc etc)
        warningMessage: "Don't spam here", // Message you get when you are warned!
        muteMessage: "was muted",// Message sent after member X was punished(muted).
       kickMessage: "was kicked", //Message sent after member X was kicked from guild!
       banMessage: "was banned", //Message sent after member X was banned from the guild!
        maxDuplicatesWarning: 7,// When people are spamming the same message, this will trigger when member X sent over 7+ messages.
        maxDuplicatesMute: 10, // The limit where member X get muted after sending too many messages(10+).
        ignoredRoles: ["Admin"], // The members with this role(or roles) will be ignored if they have it. Suggest to not add this to any random guys. Also it's case sensitive.
        ignoredMembers: ["507798218059415562"],// These members are directly affected and they do not require to have the role above. Good for undercover pranks.
        ignoreBots: true, //These bots are directly affected and they do not require to have the role above
        ignoredChannels: ["general_chat"], //These channels are directly affected
        ignorePermissions: ["ADMINISTRATOR"], //Who have admin perms are directly affected
        mutedRole: "Muted", // Here you put the name of the role that should not let people write/speak or anything else in your server. If there is no role set, by default, the module will attempt to create the role for you & set it correctly for every channel in your server. It will be named "muted".
        timeMuted: 9000 * 600, // This is how much time member X will be muted. if not set, default would be 90 min.
        logChannel: "mod-logs" // This is the channel where every report about spamming goes to. If it's not set up, it will attempt to create the channel.
      });
      
});`

**Comment by RPGTheGreat** [comment]
u need to define the client as const Antispam = require("antispam-guard")
